server:
  port: 8081
#  tomcat:
#    threads:
#      min-spare: 10
#      max: 2


app:
  cache:
    size: 365

spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
